<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C582COR" failures="3" tests="11" name="Test" time="58.905" errors="0" timestamp="2022-09-23T10:09:03 IST">
  <testcase classname="TestPackge.TestNGclass" name="opencontacttohelpcenterpage" time="2.423">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	url of contact to help center  is not working expected [https://www.messenger./] but found [https://www.messenger.com/help],
	title of page is wrong expected [Messenger Centre] but found [Messenger Help Centre]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
url of contact to help center  is not working expected [https://www.messenger./] but found [https://www.messenger.com/help],
title of page is wrong expected [Messenger Centre] but found [Messenger Help Centre]
at TestPackge.TestNGclass.opencontacttohelpcenterpage(TestNGclass.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- opencontacttohelpcenterpage -->
  <testcase classname="TestPackge.TestNGclass" name="openmessgenerpage" time="2.462">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	url of openmessnger is not working expected [https://www.messenge] but found [https://www.messenger.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
url of openmessnger is not working expected [https://www.messenge] but found [https://www.messenger.com/]
at TestPackge.TestNGclass.openmessgenerpage(TestNGclass.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- openmessgenerpage -->
  <testcase classname="TestPackge.TestNGkeywordclass" name="test3" time="0.001"/>
  <testcase classname="TestPackge.TestNGkeywordclass" name="test4" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestPackge.TestNGkeywordclass.test4(TestNGkeywordclass.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="TestPackge.TestNGkeywordclass" name="test1" time="0.0">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="TestPackge.TestNGkeywordclass" name="test2" time="0.0"/>
  <testcase classname="TestPackge.TestNGkeywordclass" name="test2" time="0.001"/>
  <testcase classname="TestPackge.TestNGkeywordclass" name="test2" time="0.001"/>
  <testcase classname="TestPackge.TestNGClass2" name="createnewaccountdisplay" time="3.831"/>
  <testcase classname="TestPackge.TestNGClass2" name="loginpagedisplay" time="3.146"/>
  <testcase classname="TestPackge.TestNGClass2" name="featurepagedisplay" time="24.404"/>
</testsuite> <!-- Test -->
